
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports eth_ref_clk]

# Analog Pin Discriptions
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports Vaux0_v_n]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports Vaux0_v_p]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports Vaux1_v_n]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports Vaux1_v_p]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports Vaux2_v_n]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports Vaux2_v_p]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS33} [get_ports Vaux4_v_n]
set_property -dict {PACKAGE_PIN C6 IOSTANDARD LVCMOS33} [get_ports Vaux4_v_p]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports Vaux5_v_n]
set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVCMOS33} [get_ports Vaux5_v_p]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports Vaux6_v_n]
set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports Vaux6_v_p]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS33} [get_ports Vaux7_v_n]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports Vaux7_v_p]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports Vaux9_v_n]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports Vaux9_v_p]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33} [get_ports Vaux10_v_n]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports Vaux10_v_p]
set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVCMOS33} [get_ports Vaux12_v_n]
set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS33} [get_ports Vaux12_v_p]
set_property -dict {PACKAGE_PIN E5 IOSTANDARD LVCMOS33} [get_ports Vaux13_v_n]
set_property -dict {PACKAGE_PIN E6 IOSTANDARD LVCMOS33} [get_ports Vaux13_v_p]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports Vaux14_v_n]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports Vaux14_v_p]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports Vaux15_v_n]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports Vaux15_v_p]


set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
